services:
  - type: web
    name: remote-alarm-server
    runtime: python
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    plan: free
